spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/book?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root@123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true



jwt.secret=beb2efbd411a959dd26a89e0a5f04e1aad7464063e540bd8a6bc1a6a1d123063